### ISSUE TITLE
This extension fails to render the tables in 11ty

### ISSUE THREAD

**Issue by gusbemacbe** [RedBug312/markdown-it-multimd-table#78]
Good afternoon!

* I use
  * Eleventy 3.1.2
  * Node.js 23.8.0
  * NPM 11.1.0
  * PNPM 10.12.4

Follow my `eleventy.js` code:

```js
// (...)
const markdown_it = require('markdown-it');
const markdown_it_abbreviation = require('markdown-it-abbr');
const markdown_it_admonition = require('markdown-it-admon');
const markdown_it_anchor = require('markdown-it-anchor');
const markdown_it_attrs = require('markdown-it-attrs');
const markdown_it_codetabs = require('markdown-it-codetabs');
const markdown_it_collapsible = require('markdown-it-collapsible');
const markdown_it_container = require('markdown-it-container');
const markdown_it_definition = require('markdown-it-deflist');
const markdown_it_footnote = require('markdown-it-footnote');
const markdown_it_kbd = require('markdown-it-kbd');
const markdown_it_mark = require('markdown-it-mark');
const markdown_it_obsidian_callouts = require('markdown-it-obsidian-callouts');
const markdown_it_sub = require('markdown-it-sub');
const markdown_it_sup = require('markdown-it-sup');
const markdown_it_table = require('markdown-it-multimd-table');
const markdown_it_toc = require('markdown-it-table-of-contents');
// (...)

module.exports = async function (eleventyConfig)
{

  // (...)

  let options = {
    html: true,
    breaks: true,
    linkify: true,
    typographer: true,
    xhtmlOut: true,
  };

  const md = markdown_it('commonmark', options).disable("code").enable('heading').enable('table')
    .use(markdown_it_abbreviation)
    .use(markdown_it_admonition)
    .use(markdown_it_anchor)
    .use(markdown_it_attrs,
      {
        leftDelimiter: '{',
        rightDelimiter: '}',
        allowedAttributes: []
      })
    .use(markdown_it_codetabs)
    .use(markdown_it_collapsible)
    .use(markdown_it_container, 'custom')
    .use(markdown_it_definition)
    .use(markdown_it_footnote)
    .use(markdown_it_kbd)
    .use(markdown_it_mark)
    .use(markdown_it_obsidian_callouts)
    .use(markdown_it_sub)
    .use(markdown_it_table,
      {
        autolabel: true,
        headerless: true,
        multibody: true,
        multiline: true,
        rowspan: true,
      })
    .use(markdown_it_toc)
    .use(markdown_it_sup)

  eleventyConfig.setLibrary('md', md);

  // (...)
};
```

And NPM/PNPM package configuration file in YAML format:

```yml
packageManager: pnpm@10.8.1
version: 1.1.1
scripts:
  build: "eleventy"
  serve: "eleventy && node server.js"
  start: "eleventy --serve --port=1864"
dependencies:
  '@11ty/eleventy-fetch': ^5.1.0
  markdown-it: ^14.1.0
  markdown-it-abbr: ^2.0.0
  markdown-it-admon: ^1.0.1
  markdown-it-anchor: ^9.2.0
  markdown-it-attrs: ^4.3.1
  markdown-it-codetabs: ^1.2.0
  markdown-it-collapsible: ^2.0.2
  markdown-it-container: ^4.0.0
  markdown-it-deflist: ^3.0.0
  markdown-it-footnote: ^4.0.0
  markdown-it-kbd: ^3.0.0
  markdown-it-mark: ^4.0.0
  markdown-it-multimd-table: ^4.2.3
  markdown-it-obsidian-callouts: ^0.3.2
  markdown-it-steps: ^0.2.0
  markdown-it-sub: ^2.0.0
  markdown-it-sup: ^2.0.0
  markdown-it-table-of-contents: ^0.9.0
  terser: ^5.43.1
devDependencies:
  '@11ty/eleventy': ^3.1.2
  '@11ty/eleventy-img': ^6.0.4
  clean-css: ^5.3.3
  compression: ^1.8.0
  express: ^5.1.0
  mocha: ^11.7.1
  serve: ^14.2.4
```

Here is the result:

![In the screenshot, it failed to render the table in MultiMarkdown using the plugin](https://github.com/user-attachments/assets/4a98a4f7-42e6-44ff-b2db-b1dd331721ed)
